### ISSUE TITLE
一个小提问

### ISSUE THREAD

**Issue by RainySY** [Closty/chaoxing#1]
关于多人签到，大大有没有想法
因为我要给一个寝室的挂，而且我的服务器又是阿里的，不能运行关于超星的脚本，所以现在就变得比较麻烦，如果可以的话，非常感谢

**Comment by reunravel** [comment]
> 关于多人签到，大大有没有想法
> 因为我要给一个寝室的挂，而且我的服务器又是阿里的，不能运行关于超星的脚本，所以现在就变得比较麻烦，如果可以的话，非常感谢

我是嫖的阿里学生机，创建了个Windows Server来挂学习通签到
www.cxsign.top
你可以试试看这个

**Comment by RainySY** [comment]
> > 关于多人签到，大大有没有想法
> > 因为我要给一个寝室的挂，而且我的服务器又是阿里的，不能运行关于超星的脚本，所以现在就变得比较麻烦，如果可以的话，非常感谢
> 
> 我是嫖的阿里学生机，创建了一个Windows Server来挂学习通
> [签到www.cxsign.top](http://www.cxsign.top)
> 你可以试试看这个

我还想问个事情，github action有没有什么限制，因为你的启发，我把我另外一个需要一直运行的python代码丢到了github action上面

**Comment by reunravel** [comment]
> > > 关于多人签到，大大有没有想法
> > > 因为我要给一个寝室的挂，而且我的服务器又是阿里的，不能运行关于超星的脚本，所以现在就变得比较麻烦，如果可以的话，非常感谢
> > 
> > 
> > 我是嫖的阿里学生机，创建了一个Windows Server来挂学习通
> > [签到www.cxsign.top](http://www.cxsign.top)
> > 你可以试试看这个
> 
> 我还想问个事情，github action有没有什么限制，因为你的启发，我把我另外一个需要一直运行的python代码丢到了github action上面

抱歉，我也不太清楚，不知道Github Action有没有执行间隔或者对网络的限制，所以还在观望

**Comment by RainySY** [comment]
> > > > 关于多人签到，大大有没有想法
> > > > 因为我要给一个寝室的挂，而且我的服务器又是阿里的，不能运行关于超星的脚本，所以现在就变得比较麻烦，如果可以的话，非常感谢
> > > 
> > > 
> > > 我是嫖的阿里学生机，创建了一个Windows Server来挂学习通
> > > [签到www.cxsign.top](http://www.cxsign.top) 
> > > 你可以试试看这个
> > 
> > 
> > 我还想问个事情，github action有没有什么限制，因为你的启发，我把我另外一个需要一直运行的python代码丢到了github action上面
> 
> 抱歉，我也不太清楚，不知道Github Action有没有执行间隔或者对网络的限制，所以还在观望

好的，麻烦你了，感谢

**Comment by reunravel** [comment]
> > > > > 关于多人签到，大大有没有想法
> > > > > 因为我要给一个寝室的挂，而且我的服务器又是阿里的，不能运行关于超星的脚本，所以现在就变得比较麻烦，如果可以的话，非常感谢
> > > > 
> > > > 
> > > > 我是嫖的阿里学生机，创建了一个Windows Server来挂学习通
> > > > [签到www.cxsign.top](http://www.cxsign.top)
> > > > 你可以试试看这个
> > > 
> > > 
> > > 我还想问个事情，github action有没有什么限制，因为你的启发，我把我另外一个需要一直运行的python代码丢到了github action上面
> > 
> > 
> > 抱歉，我也不太清楚，不知道Github Action有没有执行间隔或者对网络的限制，所以还在观望
> 
> 好的，麻烦你了，感谢

不客气

**Comment by Closty** [comment]
这是action的官方网址https://help.github.com/en/actions以及其中的限制说明https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits希望可以帮到你

**Comment by Closty** [comment]
> 这是action的官方网址https://help.github.com/en/actions
> 
> 以及其中的限制说明
> 
> https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits
> 
> 总得来说对本项目没有限制
> 
> 另外多用户网站搭建还在内测，网址：https://cx.clost.net
> 稍后会将源码上传
> 
> 希望可以帮到你
