### ISSUE TITLE
Action只能在网页端查看吗？

### ISSUE THREAD

**Issue by Echo-FL** [Closty/chaoxing#2]
- 只能在网页端查看相应的action执行是否成功吗？

- 手势签到不需要知道手势就可以签，好强。。。

**Comment by Closty** [comment]
> * 只能在网页端查看相应的action执行是否成功吗？
> * 手势签到不需要知道手势就可以签，好强。。。

第一个问题，github本质便是网页版的社区而已，但是很开源，可以通过相应的api接口进行其他方式查看包括可以自己定制的软件app。第二个问题，程序本身就是一个get请求，源于超星系统的bug，不过官方从未修复；很担心其公司对用户的隐私安全。最后，感谢您的使用，如果还有问题请回复，本issue将在未回复状态下48小时内关闭
