### ISSUE TITLE
Server酱课程通知出现错误

### ISSUE THREAD

**Issue by Echo-FL** [Closty/chaoxing#3]
- 在我测试完第一门课以后，再签到第二门，第三门课程，虽然签到成功，但是微信通知的课程名一直是第一门课程

- 签到没有错误，很及时，就是微信通知课程出现错误

**Comment by Closty** [comment]
请问，您是老师吗

> * 在我测试完第一门课以后，再签到第二门，第三门课程，虽然签到成功，但是微信通知的课程名一直是第一门课程
> * 签到没有错误，很及时，就是微信通知课程出现错误

**Comment by Echo-FL** [comment]
不是老师，是老师我干嘛搞这个。。。
这个测试很简单的，只需要两个超星账号就好了，学生也是可以创建课程的，然后电脑端在课程管理界面加人就好了（输入姓名和手机号）

**Comment by Closty** [comment]
> 不是老师，是老师我干嘛搞这个。。。
> 这个测试很简单的，只需要两个超星账号就好了，学生也是可以创建课程的，然后电脑端在课程管理界面加人就好了（输入姓名和手机号）

感谢，你让我拥有调试的方法了！

**Comment by Echo-FL** [comment]
我排查出了部分问题 
![image](https://user-images.githubusercontent.com/56504601/80584930-0933fd00-8a45-11ea-9114-12c6f93c326a.png)
我把课程名前面的改成 += 显示正确了，但是直接会显示多个，如图，
![image](https://user-images.githubusercontent.com/56504601/80585172-70ea4800-8a45-11ea-9e8e-41faa74c18f0.png)

**Comment by Closty** [comment]
> 我排查出了部分问题
> ![image](https://user-images.githubusercontent.com/56504601/80584930-0933fd00-8a45-11ea-9114-12c6f93c326a.png)
> 我把课程名前面的改成 += 显示正确了，但是直接会显示多个，如图，
> ![image](https://user-images.githubusercontent.com/56504601/80585172-70ea4800-8a45-11ea-9e8e-41faa74c18f0.png)

我还有一堆作业，可能要过几天。你可以先改，如果代码完美且在你的你同意下可以将你的代码pull过来，贡献名单将会出现你!

**Comment by Echo-FL** [comment]
![image](https://user-images.githubusercontent.com/56504601/80659746-69b25100-8abc-11ea-9c56-9eafc28f2284.png)
GitHub好像不允许，难搞

**Comment by Closty** [comment]
已经更新readme
